services:

  minio:
    image: minio/minio
    environment:
      - MINIO_CONSOLE_ADDRESS=:9001
      - MINIO_ROOT_USER=message-system
      - MINIO_ROOT_PASSWORD=message-system
    ports:
      - "3003:9000"
      - "3004:9001"
    command:
      - server
      - /data
    volumes:
      - minio-data:/data
  
  systemdb:
    image: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: message-system
      MARIADB_USERNAME: message-system
      MARIADB_PASSWORD: message-system
      MARIADB_DATABASE: message-system
    ports:
      - 3001:3306

  redis:
    image: "redis:alpine"
    ports:
      - 3002:6379  
    volumes:
      - redis_data:/data
  
  message-backend-api:
    build: messaging_api
    ports:
      - 5000:5000
    environment:
      SYSTEMDB_ADDR: systemdb
      SYSTEMDB_USERNAME: root
      SYSTEMDB_PASSWORD: message-system
      SYSTEMDB_DBNAME: message-system
      SYSTEMDB_PORT: 3306

      AWS_ACCESS_KEY: message-system
      AWS_SECRET_ACCESS_KEY: message-system

      BUCKET_NAME: message-system
      BUCKET_ENDPOINT_URL: "http://minio:9000"

volumes:
  minio-data:
  mariadb-data: 
  redis_data: